### ISSUE TITLE
Is the ground truth of pose  "relative" or "absolute"?

### ISSUE THREAD

**Issue by zhanglanqing** [ChiWeiHsiao/DeepVO-pytorch#3]
What is that original paper said about that? And what is the output pose of the network? relative or absolute? I am quite confused. hope get your reply, thanks :-)

**Comment by ChiWeiHsiao** [comment]
Hi @zhanglanqing,
It seems that the paper doesn't tell which type of pose is used.
Relative pose is used in my implementation (I also tried absolute pose but got poor result).

**Comment by zhanglanqing** [comment]
@ChiWeiHsiao I know，thanks 👍
