### ISSUE TITLE
Suggestion for improvements

### ISSUE THREAD

**Issue by alexart13** [ChiWeiHsiao/DeepVO-pytorch#4]
Thank you for your decent work! Actually your model and your code can do a bit better if you address a few logical issues in the code.
![route_04_gradient](https://user-images.githubusercontent.com/32840403/50417118-72927300-0835-11e9-8a8d-1e2052d03fce.png)
![route_06_gradient](https://user-images.githubusercontent.com/32840403/50417123-78885400-0835-11e9-8249-ba93bbb6f66e.png)
![route_07_gradient](https://user-images.githubusercontent.com/32840403/50417126-7c1bdb00-0835-11e9-8f26-49e1542c348b.png)
![route_10_gradient](https://user-images.githubusercontent.com/32840403/50417129-7f16cb80-0835-11e9-8441-9be6f692b358.png)

The issues are the following:

- In the dataloader you split a track to sequences and calculate relative coordinates and orientation. That is fine, but not enough. You should also rotate the sequence relative to the starting point angles.
- Look deeper to how the Euler angles change when the car makes a turn over 90 degrees. In such cases you can't simply subtract the angles of the previous point from the current to get the delta because the angle values are no longer continuous.

**Comment by alexart13** [comment]
Hi @ChiWeiHsiao,
I will try to find time to do that in a couple of weeks.

**Comment by shivanshrathi** [comment]
Hey @alexart13. I am a beginner in this field. I followed the steps given in your repository but after running main.py I am getting following error:
FileNotFoundError: [Errno 2] No such file or directory: '/nfs/nas12.ethz.ch/fs1201/infk_ivc_students/cvg-students/chsiao/KITTI//images/08/000001602.png'
I have already updated the parameters and path in params.py but I am getting same error over and over just with different image names. Please help when available.

**Comment by alexart13** [comment]
Hi @shivanshrathi,

Clean up the 'datainfo' folder.

**Comment by shivanshrathi** [comment]
Hey @alexart13 Thanks for the reply. The code is running now but I am getting Out of memory error. I am using a 12gb Tesla k40 gpu. Is the memory requirement more than this?

**Comment by alexart13** [comment]
@shivanshrathi the code worked for me on nvidia 1070 with 8Gb onboard

**Comment by shivanshrathi** [comment]
@alexart13 How many epochs did you train it for? Sorry for the trouble.

**Comment by alexart13** [comment]
@shivanshrathi, about 400

**Comment by la735681253** [comment]
> Thanks for the reply. The code is running now but I am getting Out of memory error. I am using a 12gb Tesla k40 gpu. Is the memory requirement more than this?

I meet the same problem . so  how to solve this problem about CUDA out of memory?

**Comment by olibd** [comment]
@alexart13 If I may ask a question, why are you applying the rotation relative to the first frame to the translation vector and not the angles?

for gt_seq in groundtruth_sequence[1:]:
      location = torch.FloatTensor(groundtruth_rotation.dot(gt_seq[3:].numpy()))
      gt_seq[3:] = location[:]
When doing [3:] you're selecting the translation portion of the array as defined on line 27 of helper.py in the R_to_angle() function. Wouldn't you want to apply it to to the quaternion portion of raw_groundtruth and then convert it to euleur and place it in gt_seq[:3]?
